### ISSUE TITLE
Existant

### ISSUE THREAD

**Issue by saucisson** [CosyVerif/paquito#1]
Afin de se renseigner sur l'existant, voici les dépôts et documents à consulter :
- [CosyVerif/images](https://github.com/CosyVerif/images) contient des scripts permettant de construire des images Docker à partir de morceaux de Dockerfiles, qu'on combine entre eux;
- [cosyverifbuildsystem](http://mbittan.github.io/cosyverifbuildsystem/) est le site correspondant au travail réalisé par les deux stagiaires de l'an dernier;
- [CosyVerif/deb-base](https://github.com/CosyVerif/deb-base) est le prototype de Paquito réalisé par les deux stagiaires de l'an dernier;
- [saucisson/hello-world](https://github.com/saucisson/hello-world) est un exemple de programme mélangeant du C++ et du C, compilé en deux passes, que vous devez intégrer dans paquito.

**Comment by melentan** [comment]
Done
